import functools
from typing import Any

import pytest
import cocotb_test.simulator
import os
import re

DIR_TESTS = os.path.join(os.path.abspath("."), "tests") # TODO: ability to change path

STUB_CODE = """
# This file was automatically generated by testtools.
# Required because of importlib's inability to import .pyi files
def __getattr__(name):
    return None
"""

def read_dependencies_file(file_path: str = "build/file_compile_order.txt") -> dict[str, list[str]]:
    """
    Read the dependecies file generated by the dependency.tcl script.
    Returns a dictionary mapping module names to a list of source files.
    """
    # TODO: fail more gracefully
    with open(file_path) as f: # TODO: ability to change path
        dependencies = f.read().split("\n")

    def parse_line(line: str) -> tuple[str, list[str]]:
        parts = line.split(" ", 1)
        if len(parts) != 2:
            raise RuntimeError(f"Could not parse dependency line: '{line}'")
        module, files = parts
        return module, files.split(":")

    return dict(parse_line(line) for line in dependencies)

def get_dependencies(verilog_module: str):
    dependencies = read_dependencies_file()

    if verilog_module in dependencies:
        return dependencies[verilog_module]
    
    raise RuntimeError(f"Could not find file compile order for module '{verilog_module}'")

def parameters_to_safe_filename(parameters: dict) -> str:
    # Sort keys for deterministic order
    unsafe = "_".join([f"{key}-{parameters[key]}" for key in sorted(parameters)])
    safe = re.sub(r'[^a-zA-Z0-9_.-]', '_', unsafe)
    return safe

def create_test(toplevel: str, filename: str, module_name: str, testcase: str | None = None, parameters: dict[str, Any] | None = None):
    def decorator(func):
        files = get_dependencies(toplevel)

        @functools.wraps(func)
        @pytest.mark.module(filename, module_name, testcase)
        def wrapper(*args, **kwargs):
            del args, kwargs  # ignore args

            # Setup stubs
            os.environ["COPRA_STUB_DIR"] = os.path.join(DIR_TESTS, "stubs")
            os.environ["COPRA_STUB_FILENAME"] = "".join((toplevel.lower(), ".pyi"))
            filename = os.path.join(DIR_TESTS, "stubs", toplevel.lower() + ".py")
            with open(filename, "w") as f:
                f.write(STUB_CODE)

            build_dir = f"build/test/simbuild_{toplevel}"
            if parameters:
                build_dir += "_" + parameters_to_safe_filename(parameters)

            cocotb_test.simulator.run(
                simulator="verilator",
                verilog_sources=files,
                toplevel=toplevel,
                module=",".join(("copra.integration.autostub", module_name)),
                includes=["."],
                compile_args=["--structs-packed", "-DSIMULATION"],
                testcase=testcase,
                # Different simbuild dir to utilize cache on each module
                sim_build=build_dir, # TODO: ability to change path
                python_search=[DIR_TESTS],
                parameters=parameters,
            )

        return wrapper

    return decorator
