from __future__ import annotations
import cocotb.handle
import cocotb.types
from typing import overload, Literal

# This file was automatically generated by copra
# It provides type stubs for your HDL design for use with cocotb

class Adder(cocotb.handle.HierarchyObject):
    a: cocotb.handle.LogicArrayObject
    b: cocotb.handle.LogicArrayObject
    sum: cocotb.handle.LogicArrayObject

    @overload
    def __getitem__(self, name: Literal['a']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['b']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['sum']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...

