from __future__ import annotations
import cocotb.handle
import cocotb.types
from typing import overload, Literal

# This file was automatically generated by copra
# It provides type stubs for your HDL design for use with cocotb

class Binarytogray(cocotb.handle.HierarchyObject):
    WIDTH: cocotb.handle.LogicArrayObject
    binary: cocotb.handle.LogicArrayObject
    gray: cocotb.handle.LogicArrayObject

    @overload
    def __getitem__(self, name: Literal['WIDTH']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['binary']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['gray']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...

