from __future__ import annotations
import cocotb.handle
import cocotb.types
from typing import overload, Literal

# This file was automatically generated by copra
# It provides type stubs for your HDL design for use with cocotb

class Pointersynchronizer(cocotb.handle.HierarchyObject):
    WIDTH: cocotb.handle.LogicArrayObject
    binary_to_gray: BinaryToGray
    clk_dest: cocotb.handle.LogicObject
    data_in: cocotb.handle.LogicArrayObject
    data_out: cocotb.handle.LogicArrayObject
    gray_data: cocotb.handle.LogicArrayObject
    gray_to_binary: GrayToBinary
    rstn: cocotb.handle.LogicObject
    sync1: cocotb.handle.LogicArrayObject
    sync2: cocotb.handle.LogicArrayObject

    @overload
    def __getitem__(self, name: Literal['WIDTH']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['clk_dest']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['data_in']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['data_out']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['gray_data']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['rstn']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['sync1']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['sync2']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['binary_to_gray']) -> BinaryToGray: ...

    @overload
    def __getitem__(self, name: Literal['gray_to_binary']) -> GrayToBinary: ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...


class BinaryToGray(cocotb.handle.HierarchyObject):
    WIDTH: cocotb.handle.LogicArrayObject
    binary: cocotb.handle.LogicArrayObject
    gray: cocotb.handle.LogicArrayObject

    @overload
    def __getitem__(self, name: Literal['WIDTH']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['binary']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['gray']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...


class GrayToBinary(cocotb.handle.HierarchyObject):
    WIDTH: cocotb.handle.LogicArrayObject
    binary: cocotb.handle.LogicArrayObject
    gray: cocotb.handle.LogicArrayObject

    @overload
    def __getitem__(self, name: Literal['WIDTH']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['binary']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['gray']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...

