from __future__ import annotations
import cocotb.handle
import cocotb.types
from typing import overload, Literal

# This file was automatically generated by copra
# It provides type stubs for your HDL design for use with cocotb

class Spisub(cocotb.handle.HierarchyObject):
    RX_QUEUE_LENGTH: cocotb.handle.LogicArrayObject
    TX_QUEUE_LENGTH: cocotb.handle.LogicArrayObject
    WORD_SIZE: cocotb.handle.LogicArrayObject
    active: cocotb.handle.LogicObject
    bit_count: cocotb.handle.LogicArrayObject
    data_ready: cocotb.handle.LogicObject
    load_new_tx: cocotb.handle.LogicObject
    miso: cocotb.handle.LogicObject
    mosi: cocotb.handle.LogicObject
    pop_new_tx: cocotb.handle.LogicObject
    rstn: cocotb.handle.LogicObject
    rx_buffer: cocotb.handle.LogicArrayObject
    rx_data: cocotb.handle.LogicArrayObject
    rx_data_en: cocotb.handle.LogicObject
    rx_queue: RxQueue
    rx_queue_empty: cocotb.handle.LogicObject
    rx_ready: cocotb.handle.LogicObject
    rx_shift_register: RxShiftRegister
    sclk: cocotb.handle.LogicObject
    ssn: cocotb.handle.LogicObject
    sys_clk: cocotb.handle.LogicObject
    sys_rstn: cocotb.handle.LogicObject
    tx_buffer: cocotb.handle.LogicArrayObject
    tx_data: cocotb.handle.LogicArrayObject
    tx_data_en: cocotb.handle.LogicObject
    tx_queue: TxQueue
    tx_queue_full: cocotb.handle.LogicObject
    tx_ready: cocotb.handle.LogicObject
    tx_shift_register: TxShiftRegister

    @overload
    def __getitem__(self, name: Literal['RX_QUEUE_LENGTH']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['TX_QUEUE_LENGTH']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['WORD_SIZE']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['active']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['bit_count']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['data_ready']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['load_new_tx']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['miso']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['mosi']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['pop_new_tx']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['rstn']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['rx_buffer']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['rx_data']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['rx_data_en']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['rx_queue_empty']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['rx_ready']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['sclk']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['ssn']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['sys_clk']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['sys_rstn']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['tx_buffer']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['tx_data']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['tx_data_en']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['tx_queue_full']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['tx_ready']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['rx_queue']) -> RxQueue: ...

    @overload
    def __getitem__(self, name: Literal['rx_shift_register']) -> RxShiftRegister: ...

    @overload
    def __getitem__(self, name: Literal['tx_queue']) -> TxQueue: ...

    @overload
    def __getitem__(self, name: Literal['tx_shift_register']) -> TxShiftRegister: ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...


class RxQueue(cocotb.handle.HierarchyObject):
    ADDRESS_WIDTH: cocotb.handle.LogicArrayObject
    LENGTH: cocotb.handle.LogicArrayObject
    MIN_LENGTH: cocotb.handle.LogicArrayObject
    WIDTH: cocotb.handle.LogicArrayObject
    data_in: cocotb.handle.LogicArrayObject
    data_out: cocotb.handle.LogicArrayObject
    empty: cocotb.handle.LogicObject
    fifo: cocotb.handle.ArrayObject[cocotb.types.LogicArray, cocotb.handle.LogicArrayObject]
    full: cocotb.handle.LogicObject
    read_clk: cocotb.handle.LogicObject
    read_en: cocotb.handle.LogicObject
    read_ptr: cocotb.handle.LogicArrayObject
    read_ptr_synced: cocotb.handle.LogicArrayObject
    read_synchronizer: ReadSynchronizer
    rstn: cocotb.handle.LogicObject
    write_clk: cocotb.handle.LogicObject
    write_en: cocotb.handle.LogicObject
    write_ptr: cocotb.handle.LogicArrayObject
    write_ptr_synced: cocotb.handle.LogicArrayObject
    write_synchronizer: WriteSynchronizer

    @overload
    def __getitem__(self, name: Literal['ADDRESS_WIDTH']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['LENGTH']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['MIN_LENGTH']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['WIDTH']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['data_in']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['data_out']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['empty']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['fifo']) -> cocotb.handle.ArrayObject[cocotb.types.LogicArray, cocotb.handle.LogicArrayObject]: ...

    @overload
    def __getitem__(self, name: Literal['full']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['read_clk']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['read_en']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['read_ptr']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['read_ptr_synced']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['rstn']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['write_clk']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['write_en']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['write_ptr']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['write_ptr_synced']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['read_synchronizer']) -> ReadSynchronizer: ...

    @overload
    def __getitem__(self, name: Literal['write_synchronizer']) -> WriteSynchronizer: ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...


class ReadSynchronizer(cocotb.handle.HierarchyObject):
    WIDTH: cocotb.handle.LogicArrayObject
    binary_to_gray: BinaryToGray
    clk_dest: cocotb.handle.LogicObject
    data_in: cocotb.handle.LogicArrayObject
    data_out: cocotb.handle.LogicArrayObject
    gray_data: cocotb.handle.LogicArrayObject
    gray_to_binary: GrayToBinary
    rstn: cocotb.handle.LogicObject
    sync1: cocotb.handle.LogicArrayObject
    sync2: cocotb.handle.LogicArrayObject

    @overload
    def __getitem__(self, name: Literal['WIDTH']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['clk_dest']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['data_in']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['data_out']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['gray_data']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['rstn']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['sync1']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['sync2']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['binary_to_gray']) -> BinaryToGray: ...

    @overload
    def __getitem__(self, name: Literal['gray_to_binary']) -> GrayToBinary: ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...


class BinaryToGray(cocotb.handle.HierarchyObject):
    WIDTH: cocotb.handle.LogicArrayObject
    binary: cocotb.handle.LogicArrayObject
    gray: cocotb.handle.LogicArrayObject

    @overload
    def __getitem__(self, name: Literal['WIDTH']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['binary']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['gray']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...


class GrayToBinary(cocotb.handle.HierarchyObject):
    WIDTH: cocotb.handle.LogicArrayObject
    binary: cocotb.handle.LogicArrayObject
    gray: cocotb.handle.LogicArrayObject

    @overload
    def __getitem__(self, name: Literal['WIDTH']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['binary']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['gray']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...


class WriteSynchronizer(cocotb.handle.HierarchyObject):
    WIDTH: cocotb.handle.LogicArrayObject
    binary_to_gray: BinaryToGray
    clk_dest: cocotb.handle.LogicObject
    data_in: cocotb.handle.LogicArrayObject
    data_out: cocotb.handle.LogicArrayObject
    gray_data: cocotb.handle.LogicArrayObject
    gray_to_binary: GrayToBinary
    rstn: cocotb.handle.LogicObject
    sync1: cocotb.handle.LogicArrayObject
    sync2: cocotb.handle.LogicArrayObject

    @overload
    def __getitem__(self, name: Literal['WIDTH']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['clk_dest']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['data_in']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['data_out']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['gray_data']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['rstn']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['sync1']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['sync2']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['binary_to_gray']) -> BinaryToGray: ...

    @overload
    def __getitem__(self, name: Literal['gray_to_binary']) -> GrayToBinary: ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...


class RxShiftRegister(cocotb.handle.HierarchyObject):
    SIZE: cocotb.handle.LogicArrayObject
    buffer: cocotb.handle.LogicArrayObject
    clk: cocotb.handle.LogicObject
    parallel_in: cocotb.handle.LogicArrayObject
    parallel_in_en: cocotb.handle.LogicObject
    parallel_out: cocotb.handle.LogicArrayObject
    rstn: cocotb.handle.LogicObject
    serial_in: cocotb.handle.LogicObject
    serial_out: cocotb.handle.LogicObject

    @overload
    def __getitem__(self, name: Literal['SIZE']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['buffer']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['clk']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['parallel_in']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['parallel_in_en']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['parallel_out']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['rstn']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['serial_in']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['serial_out']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...


class TxQueue(cocotb.handle.HierarchyObject):
    ADDRESS_WIDTH: cocotb.handle.LogicArrayObject
    LENGTH: cocotb.handle.LogicArrayObject
    MIN_LENGTH: cocotb.handle.LogicArrayObject
    WIDTH: cocotb.handle.LogicArrayObject
    data_in: cocotb.handle.LogicArrayObject
    data_out: cocotb.handle.LogicArrayObject
    empty: cocotb.handle.LogicObject
    fifo: cocotb.handle.ArrayObject[cocotb.types.LogicArray, cocotb.handle.LogicArrayObject]
    full: cocotb.handle.LogicObject
    read_clk: cocotb.handle.LogicObject
    read_en: cocotb.handle.LogicObject
    read_ptr: cocotb.handle.LogicArrayObject
    read_ptr_synced: cocotb.handle.LogicArrayObject
    read_synchronizer: ReadSynchronizer
    rstn: cocotb.handle.LogicObject
    write_clk: cocotb.handle.LogicObject
    write_en: cocotb.handle.LogicObject
    write_ptr: cocotb.handle.LogicArrayObject
    write_ptr_synced: cocotb.handle.LogicArrayObject
    write_synchronizer: WriteSynchronizer

    @overload
    def __getitem__(self, name: Literal['ADDRESS_WIDTH']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['LENGTH']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['MIN_LENGTH']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['WIDTH']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['data_in']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['data_out']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['empty']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['fifo']) -> cocotb.handle.ArrayObject[cocotb.types.LogicArray, cocotb.handle.LogicArrayObject]: ...

    @overload
    def __getitem__(self, name: Literal['full']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['read_clk']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['read_en']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['read_ptr']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['read_ptr_synced']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['rstn']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['write_clk']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['write_en']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['write_ptr']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['write_ptr_synced']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['read_synchronizer']) -> ReadSynchronizer: ...

    @overload
    def __getitem__(self, name: Literal['write_synchronizer']) -> WriteSynchronizer: ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...


class TxShiftRegister(cocotb.handle.HierarchyObject):
    SIZE: cocotb.handle.LogicArrayObject
    buffer: cocotb.handle.LogicArrayObject
    clk: cocotb.handle.LogicObject
    parallel_in: cocotb.handle.LogicArrayObject
    parallel_in_en: cocotb.handle.LogicObject
    parallel_out: cocotb.handle.LogicArrayObject
    rstn: cocotb.handle.LogicObject
    serial_in: cocotb.handle.LogicObject
    serial_out: cocotb.handle.LogicObject

    @overload
    def __getitem__(self, name: Literal['SIZE']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['buffer']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['clk']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['parallel_in']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['parallel_in_en']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['parallel_out']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['rstn']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['serial_in']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['serial_out']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...

